name: Update Repository Information

# NOTE: This workflow requires a Personal Access Token (PAT) with 'repo' scope
# You need to add a secret named 'PAT' in your repository settings

on:
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      description:
        description: 'Repository description'
        required: false
        default: 'A React application built with Vite and deployed to GitHub Pages'
      topics:
        description: 'Repository topics (comma-separated)'
        required: false
        default: 'react,vite,github-pages,javascript,web-development'

jobs:
  update-repo-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update repository description and topics
        run: |
          # Set description
          DESCRIPTION="${{ github.event.inputs.description || 'A React application built with Vite and deployed to GitHub Pages' }}"
          echo "Setting repository description to: $DESCRIPTION"
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d "{\"description\":\"$DESCRIPTION\"}"
          
          # Set topics
          TOPICS="${{ github.event.inputs.topics || 'react,vite,github-pages,javascript,web-development' }}"
          echo "Setting repository topics to: $TOPICS"
          # Convert comma-separated to JSON array format
          TOPICS_JSON=$(echo $TOPICS | sed 's/,/","/g' | sed 's/^/["/' | sed 's/$/"]/')
          curl -X PUT \
            -H "Authorization: token ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.mercy-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/topics \
            -d "{\"names\":$TOPICS_JSON}"
